name: kurakani
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
#  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # GetX
  get: ^4.6.1

  # date
  intl: ^0.20.0

  # device ui resizing
  flutter_screenutil: ^5.3.1

  # pull to refresh
  pull_to_refresh: ^2.0.0

  # toast
  fluttertoast: ^8.0.9

  # easyloading
  flutter_easyloading: ^3.0.3

  # http
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  # local storage
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  # encrypting SHA
  crypto: ^3.0.1

  # webView
  webview_flutter: ^4.0.0

  # loading
  loading_animations: ^2.2.0

  # share
  share_plus: ^7.2.1

  # device info
  device_info_plus: ^11.3.0

  # package info
  package_info_plus: ^8.0.2

  #path
  path_provider: ^2.0.9

  # permission
  permission_handler: ^11.3.1

  # about errors
  sentry: ^8.9.0

  # get data about device
  app_links: ^3.5.0

  #animation library
  flutter_spinkit: ^5.1.0


  dots_indicator: ^3.0.0

  google_sign_in: ^6.2.1

  firebase_core: ^3.6.0

  firebase_messaging: ^15.1.3

  firebase_in_app_messaging: ^0.8.0+8

  firebase_auth: ^5.3.1

  cloud_firestore: ^5.4.4

  firebase_storage: ^12.3.2

  location: ^6.0.2

  image_picker: ^1.1.2

  photo_view: ^0.15.0

  sqflite: ^2.0.3+1

  flutter_verification_code: ^1.1.6

  agora_rtc_engine: ^6.1.0

  just_audio: ^0.9.30

#  flutter_local_notifications: ^17.2.4
  uuid: ^4.5.1
  zego_uikit_prebuilt_call: ^4.4.0
  zego_express_engine: ^3.17.1
  awesome_notifications: ^0.10.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
